### ISSUE TITLE
Prevents parallel Babel

### ISSUE THREAD

**Issue by ef4** [ember-template-lint/ember-cli-template-lint#444]
The `remove-configuration-html-comments` AST plugin from this addon gets detected by ember-cli-htmlbars-inline-precompile as a reason why [it shouldn't allow parallel babel](https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/4aa23e5215333f17db7ba2a61eb0c82d8c26883a/index.js#L83) transpilation.

**Comment by rwjblue** [comment]
Seems odd, is this due to a mismatch between babel-plugin-htmlbars-inline-precompile's caching system and the one used by broccoli-babel-transpiler?

Also, as an aside, I am planning on removing `ember-cli-template-lint` from the default application in favor of using `ember-template-lint` directly. This change would automatically make the issue you hit invalid (since there would be no addon interop at all).

**Comment by ef4** [comment]
I don't think this is about caching in inline-precompile.

AFAIK, we don't have any support for doing template compilation in parallel. The normal way to register AST transforms results in the whole template compilation being non-serializable so you can't move it to another process.

inline-precompile is weird because it moves the template compilation inside babel, and our babel _does_ have parallelization support. That works until somebody registers an AST transform.

**Comment by rwjblue** [comment]
> I don't think this is about caching in inline-precompile.

Hmm, I think it has to be due to inline precompile. Without the inline precompile plugin template compilation never goes through broccoli-babel-transpiler on its own (and therefore cannot prevent parallelization).

> inline-precompile is weird because it moves the template compilation inside babel, and our babel _does_ have parallelization support

inline-precompile doesn't move _all_ template compilation into babel land, only templates in `hbs` inside .js files...

**Comment by ef4** [comment]
> Hmm, I think it has to be due to inline precompile.

Oh yeah, I didn't mean to disagree with that, this definitely involves inline-precompile. I was just saying it's not related to any _caching_ in inline-precompile.

> inline-precompile doesn't move _all_ template compilation into babel land, only templates in `hbs` inside .js files...

Correct, but AFAIK even those inline templates are supposed to get processed with any AST transforms you have configured. As long as that's true, the presence of an AST transform being used inside an inline template makes the babel transpilation non-parallelizable.

**Comment by ef4** [comment]
I guess this may not be a bug in ember-template-lint. I'm unclear on whether it's actually possible to author an AST transform such that it will not trip this issue in inline-precompile.

The code in inline-precompile implies that it's possible set a `parallelBabel` property on your ast transforms to avoid the problem, but I don't fully understand if that's actually implemented or what supports it. Also, that seems like a bad name for the feature, when it's really about parallelizing AST transformation.
