### ISSUE TITLE
Rule: Disallow mustaches/subexpr in partials.

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-cli-template-lint#86]
Dynamic lookups in partials quickly become untenable because they have absolutely no limitations to the things they can reach out and "get". It also becomes nearly impossible to refactor the template/controller/component invoking the partial  without completely internalizing absolutely everything since they have no established API.

Good:

``` hbs
{{! some-path/-blah.hbs }}
{{! no dynamic lookups here}}
<svg></svg>
```

Bad:

``` hbs
{{! some-path/-blah.hbs }}
{{! oh no dynamic lookups here!! }}
<div>{{foo}}</div>
```

**Comment by oriSomething** [comment]
i'm not sure about this rule, since the performance of components is quite limited comparing to partials (it's more of my guess than i actually pref this assumption).
also, in case there is no dynamic content in partial it seems makes partials useless, exclude when you want to inline an SVG logo.
in that case, maybe making the use of partials should be forbidden, since for most cases there is no need to use them since they make only confuse (especially in ember-cli projects).

**Comment by rwjblue** [comment]
Yes, SVG inclusion is exactly the reason I don't want to block completely. 

Partials with dynamic segments are basically impossible to use outside of their original location because they assume full scop. At that point what is the point of it? Better to provide an actual API so you can reason about it (via a component).

RE: perf, let's just fix the perf is that is a legit concern.

**Comment by oriSomething** [comment]
so maybe there should be some levels of this rule:
1. disallow partial for any reason
2. allow only when there is no dynamic content
3. allow it (be sure you know why you're using it)

**Comment by rwjblue** [comment]
Right:

1: disallow usage of {{partial
2: detect dynamic invocation in _ or - prefixed templates
3: would just be disabling the rule.

**Comment by oriSomething** [comment]
you've just reminded me that in older ember-cli apps i made there are partials without prefixes. maybe it should be it's own rule (disallow using templates with `{{partial}}` that don't have `_` or `-` prefix)

**Comment by Turbo87** [comment]
moved to https://github.com/ember-template-lint/ember-template-lint/issues/386
